### PR TITLE
Search for consecutive pairs of words using the single word offset index

### PR DESCRIPTION
**Pull request by chrisgemignani**
Loved the talk today. 

Here's how I was thinking about doing a simple search for word pairs. They are arbitrarily weighted 50x higher than single words. This is so Billy Jean King can win her searches.

**Added tuple searching**
```
→ python3 cmdline.py large-sample/
search:> billy jean
       35.2 Billie-Jean-King.txt
       32.0 Wyclef-Jean.txt
       26.2 Billy-Joel.txt
       14.5 List-of-Tachinidae-genera.txt
       12.1 Union-for-a-Popular-Movement.txt
       12.1 Jean%2DPaul-Sartre.txt
       10.7 Nationalist-Party-of-Australia.txt
       10.1 Christianity-Today.txt
        9.7 The-Smashing-Pumpkins.txt
        9.4 FC-Nantes.txt
```

**Original**
```
search:> billy jean
       32.0 Wyclef-Jean.txt
       26.2 Billy-Joel.txt
       14.5 List-of-Tachinidae-genera.txt
       12.1 Union-for-a-Popular-Movement.txt
       12.1 Jean%2DPaul-Sartre.txt
       11.1 Billie-Jean-King.txt
       10.7 Nationalist-Party-of-Australia.txt
       10.1 Christianity-Today.txt
        9.7 The-Smashing-Pumpkins.txt
        9.4 FC-Nantes.txt
```

### CODE REVIEW

**Comment by jorendorff** [comment]
Sweet!

**Comment by jorendorff** [comment]
Changing the fudge factor from 50 to 500 is enough to push Nashville over Batman and the Billboard Hot 100. I'm calling it - @chrisgemignani wins the contest!

**Comment by chrisgemignani** [comment]
@jorendorff I had also tried adding tuples to the index and that ran me out of memory even with stopwords.

**Comment by jorendorff** [comment]
Cool - that makes sense. I never considered it, figuring that would be the case. But really, I guess adding 2-tuples would "only" double the size of the index.

I can drop off your prize today, tomorrow, or Thursday. Let me know when you'll be in the office. (You can find me on the nashdev slack or just get Jason Myers to ping me.)

**Comment by jorendorff** [comment]
...Well, maybe it's much worse than double, since more pairs will be unique than words, and unique items cost more to store (new instances of words that already exist in the index are cheap, 4 or 12 bytes).

**Pull request closed without merging**
