### PR TITLE
fix more Python 3.5 things

### PR DESCRIPTION
**Pull request by blbradley**
Howdy!

I had an error like `ValueError: invalid file PosixPath('small-sample/.tiny/documents.csv')`.

This fixed it. Woohoo!

### CODE REVIEW

**Comment by blbradley** [comment]
I got another error when I used the query form. Please hold.

**Comment by blbradley** [comment]
No errors on query!

**Comment by chrisgemignani** [comment]
:+1:

**Comment by jorendorff** [comment]
Oh, of course. Thank you!

**Pull request merged**
